title: "A História de Cristiano Ronaldo"
description: "A jornada de Cristiano Ronaldo, de Madeira ao topo do futebol mundial"
baseurl: ""
url: "https://caio741.github.io"
theme: minima
author:
  name: "Caio"
  email: ""
